README.md
=> Update readme to remove reference to evervault_client

README.md
making python readme consistent with docs
=> update python readme

evervault/version.py
Bump package version for release
Bump version.py
=> Bump package version

evervault/version.py
Should have bumped version in last PR. Deployed version is `0.1.4`, just making sure the repo is consistent.
0.1.4
=> Bump version

evervault/version.py
We need to deploy this to make requests work and to put in the change for deterministic encryption
Bumping version, also making sure that this is good to go
cc @DeirdreCleary
=> Prepare for deploy

README.md, evervault/__init__.py, evervault/client.py
Match Node SDK. Cleaner Docs.
Change parameter of `run` functions. Update README
=> `encrypted_data` -> `data` in Python SDK `evervault.run()`

README.md
Update docs to reflect retry option
=> Update docs to reflect retry option

README.md
=> fix(docs): update example to include retry

README.md
Release support for new errors exposed by runtime
Trigger release with docs update
=> fix: release new runtime error support

README.md
We didn't make explicit reference to commitizen in the repo
Reference commitizen in readme
=> Include reference to commitizen and contributing.md

README.md, evervault/client.py, evervault/http/requesthandler.py, tests/test_handling_requests.py
Reverts evervault/evervault-python#57
=> Revert "Jhonny/ev 832 assure the sdk does not make a call"

evervault/http/requestintercept.py, tests/test_evervault.py
Reverts evervault/evervault-python#63
Sem ver is different for python and it's not picking up commits for the release
=> Revert "Fix: Respect ignore domains list"

evervault/http/requestintercept.py, tests/test_evervault.py
Need to check the ignore domains properly
- Use client self instead of request self
- Add tests
=> fix: respect ignore domains list

README.md, evervault/http/requestintercept.py, tests/test_evervault.py
Add a short description about this PR.
Add links to issues, tech plans etc.
Adds support for wildcard decryption domains
=> feat(outbound): Supports wildcard decryption domains

pyproject.toml
Super minor typo fix. Feel free to ignore completely or fix yourselves as part of another release. Didn't seem worthy of GH issue...
=> chore(manifest): fixes typo in pyproject.toml description.

.gitignore, README.md, evervault/__init__.py, evervault/client.py, evervault/http/requestintercept.py, tests/test_evervault.py
Reverts evervault/evervault-python#72
=> Revert "Pull relay config from API"

README.md, evervault/__init__.py
- UI based outbound relay config is not ready for production
- Revert deprecation warning
- Update README
=> fix: remove decryption domains from whitelist

evervault/__init__.py
Provide a default value for data argument
=> fix(create_run_token): provide default value for data argument

.github/workflows/release.yml, poetry.lock
- Release decrypt function
- Bump poetry version
- Regenerate lock file for new poetry version
=> feat!: Release decrypt function

CHANGELOG.md, pyproject.toml
This reverts commit ca2679afb5a9093bbb0377f317e8d09bc178c6bd.
Add a short description about this PR.
Add links to issues, tech plans etc.
=> Revert "chore: Revert 3.0.0"

evervault/__init__.py
=> chore: bump version

.changeset/shaggy-actors-dance.md
Release attestation doc version bump
Add changeset
=> Release attestation doc version bump

.changeset/four-pans-ring.md, .changeset/fresh-flies-drive.md, .changeset/new-pugs-smoke.md, .changeset/small-games-rest.md
The original changeset messages were not clear enough for user consumption
Updated changeset messages
=> Increasing clarity in changeset

.changeset/ninety-rivers-beam.md, evervault/__init__.py, evervault/client.py, tests/test_evervault.py
To support asynchronous Function run functionality, Fixes ETR-1609
=> Add async Function run support
