evervault/client.py, evervault/version.py
After testing using the outbound Relay on the pypi test server I noticed that strangely the previous method for verifying the relay certificate wasn't working on `Python 3.8.10`+ versions. Latest versions of Python seem very hardcore about only using the `certifi` root CAs file.
Append Evervault root CA to the `certifi` list of trusted CAs. Tested this new method on Ubuntu and Mac and it works but I included manual install instructions in the error message in case write access for the `certifi` CA file is unavailable.
=> Append cert for outbound Relay to Certifi trusted CAs file

README.md, evervault/__init__.py, evervault/client.py
Clients would like the ability to give a list of target domains with the effect that requests sent to these domains won't get sent through Outbound Relay
Note: current configuration works such that if a target URL sent in a request cannot be parsed, it will default to go through Relay. I figured it is highly unlikely clients would be making strange requests toward their `ignore_domains`, so better to handle the edge cases by sending them through Relay as default (I also think these edge cases may never occur because if `urlparse` can't parse it then I think this will cause further errors at lower levels).
_Readme update:_
You may also optionally pass in a list of domains which you **don't** want to go through Relay, i.e. requests sent to these domains will not be decrypted.
```python …
```
=> Add ability to give list of domains not to send through Outbound Relay

evervault/client.py
I thought params passed in as None would take the default value specified in the function.
```python
def fun(param={}):
if param is None: param = {}
```
=> Handle params passed in as None

evervault/client.py, evervault/version.py
File write issues
@shanecurran solved it by appending the Evervault root cert to the `certifi` trusted roots and storing in temp file (`version` is bumped by a few because I deployed a couple of times earlier without bumping repo)
=> Make outbound relay work in python sdk

evervault/client.py, evervault/version.py
Remembered that I forgot to update the error message :unamused:
`Unable to install the Evervault root certficate from {cert_host}. Likely a permissions error when attempting to write to the /tmp/ directory.`
=> Update cert install error message

evervault/client.py, evervault/version.py
Data should only be decrypted when it reaches the cage
```python
ignore_domains.append(urlparse(client_self.base_run_url).netloc)
```
=> Dont send requests to cages through Relay (Python SDK)

evervault/__init__.py, evervault/client.py, evervault/version.py, tests/test_evervault.py
Currently using old `cages.run` url
Replace with `run.evervault.com`
=> Update Python SDK to send Cage runs to run.evervault.com

evervault/client.py
There was an issue in requests 2.26.0 where a function `rebuild_proxies` was called before a request, which caused the `Proxy-Authorization` header to be removed (since it is not password based). 
This function has just been overriden to do nothing, since all of its functions are already handled on our side.
=> Override proxy rebuild method to fix API key being removed from requests

README.md, evervault/__init__.py, tests/test_evervault.py
Easier for users to integrate their API with Evervault. Just point Relay at their API and initialize the SDK in their API.
* Switch to using `evervault.init('<YOUR-API-KEY>')` function instead of setting `evervault.api_key='<YOUR-API-KEY>'`. This allows us to choose whether to use Relay when the SDK is initialized. Also more similar to Node SDK.
* Switch to using `intercept = False` as the parameter to turn off Relay intercepting requests. `evervault.init('<YOUR-API-KEY>', intercept=False)`
* `ignore_domains` can be passed in `evervault.init` also: `evervault.init('<YOUR-API-KEY>', ignore_domains=['httpbin.org'])`
=> Default outbound relay to ON in Python SDK

evervault/__init__.py
Old error message wasn't informative. This will also help users to know what to do when updating from `evervault.api_key` -> `evervault.init()`
`"Your Team's API Key must be entered using evervault.init('<API-KEY>')"`
=> Return better error message when user doesn't enter API key

README.md
Method call was in camel case
Updated to lower case with underscores per example and source code
=> Correcting encrypt_and_run method call in readme

README.md
encrypt_and_run and cages are both deprecated
Removed them from the readme
=> Removing deprecated endpoints from readme

evervault/client.py
Adds the domain to the ignore list.
=> Stop `ca.evervault.com` from going through Relay

evervault/client.py
Certain errors such as socket hangups can be retried client side.
Approach for if it fails is just to try again, and only error if that doesn't work too
=> Retry getting the CA if it fails once

evervault/__init__.py, evervault/client.py, evervault/version.py, tests/test_evervault.py
Support custom non production endpoints for development and load testing
Check for the presence of EV_API_URL, EV_CAGE_RUN_URL and EV_TUNNEL_HOSTNAME else use the default production values
port of https://github.com/evervault/evervault-node/pull/59
=> Support overrides of evervault endpoints via env variables

.github/workflows/release.yml, .github/workflows/test.yml, CONTRIBUTING.md, evervault/client.py, evervault/crypto/client.py, evervault/http/metrics.py, tests/test_evervault.py
To better support our SDK development, we need to have some insight on how the SDKs are getting used.
This PR adds a non-blocking metrics reporter (runs in a different thread). This will batch encrypt metric notifications and run periodically, and will only block if the application is stopping and there are some requests left to send.
=> Add Encrypt Metrics Reporting

.github/pull_request_template.md, CONTRIBUTING.md
Some changes were made with respect to how development is done in this repository, to bring it more in line with the Node SDK. These changes needed to be documented.
A `CONTRIBUTING.md` was added, along with a checklist for the conventional commits style (to make sure everything remains compatible with semantic-release).
=> Add a `CONTRIBUTING.md` and checklist to the PR template

evervault/__init__.py, evervault/client.py, evervault/http/request.py
Allow users to optionally enable retries for fetching the Evervault root cert and cage operations.
Added an optional `retry` parameter to the `init()` function. 
If retries are enabled, cage operations and cert fetching will retry up to 3 times.
=> feat: Add optional retries to requests for cert and cage operations

.github/workflows/release.yml
Semantic release needs the access token passed to checkout: from [here](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html).
- Add token
=> fix(actions): add access token to checkout

evervault/errors/error_handler.py, evervault/errors/evervault_errors.py
New errors are being sent from the cage run api
Added handling of new errors
=> Adding new cage errors 408 and 422

evervault/__init__.py, evervault/errors/error_handler.py, evervault/errors/evervault_errors.py, pyproject.toml, tests/test_evervault.py
Adding support for the Python SDK to handle Forbidden IP address responses from the Cage run api
Check the evervault error code from the Cage run response on a 403 response
=> add error type for rejected IP address

evervault/__init__.py, pyproject.toml
Cert check code for lambda error is non functional
Removed commits that introduced code.
=> fix: remove code for cert check

evervault/http/requestintercept.py, tests/test_evervault.py
Ignore domains doesn't work because self being used was of the request and not the client so the domains weren't matching up when they were checked.
Pass the correct values
=> Fix: Respect ignore domains list

evervault/http/requestintercept.py
Python SDK wasn't emptying the proxies list for each request, this led to some requests being sent through outbound that weren't meant to be sent through there.
This manifested in an issue when running the sdk inside of aws lambdas because the initial request to `ca.evervault.com` would be proxied through outbound if a proxied request occurred in any previous invocation.
Reset the proxies list for each request.
=> fix: empty proxies for each request

evervault/http/repeated_timer.py, evervault/http/requestintercept.py
Thread is spawning in a loop calling the API recursively
Use a Daemon timer which will check if it running before starting a new thread
=> Fix: Don't spawn thread in loop

evervault/http/repeated_timer.py, evervault/http/requestintercept.py
- Semantic release didn't deploy previous merge. 
- #75 
- Trying again
=> fix: store thread spawing on each call to init

evervault/http/repeated_timer.py, evervault/http/requestintercept.py, tests/test_repeated_timer.py
Recursive call to create thread was creating multiple timers.
- Create `RepeatedTimer` class which uses `Thread.Timer` to call for outbound relay config.
=> fix: Replace recursive timer call with RepeatedTimer class

README.md, evervault/__init__.py, evervault/client.py, evervault/http/requestintercept.py
Python SDK currently doesn't support aiohttp async requests.
Added an option to provide an aiohttp Client for the SDK to wrap when enabling outbound Relay.
=> Support aiohttp async requests in Python

README.md
Latest release (1.7.0) included the cage requests session but the readme wasn't updated to reflect the changes
Update readme to include docs on how to call your cage over an attested connection
=> Update readme with cage requests session info

pyproject.toml
Current version of python's cryptography package has a [vulnerability](https://github.com/advisories/GHSA-w7pp-m8wf-vj6r). This vulnerability is not exposed through this package as we do not consume this API, but we are many versions behind latest so it is worth updating.
- Bump cryptography dependency to latest (39.0.1)
- Mark as a Breaking Change due to reduced platform support from cryptography dependency.
The following breaking changes have occurred in the cryptography package since 3.4.8:
- Support for OpenSSL 1.1.0 has been removed. Users on older version of OpenSSL will need to upgrade.
- Dropped support for LibreSSL < 3.5. The new minimum LibreSSL version is 3.5.0. Going forward our policy is to support versions of LibreSSL that are available in versions of OpenBSD that are still …
=> fix!: update cryptography dependency to remove vuln

evervault/__init__.py
Run tokens should be able to be created without pre-approved payloads
Allow users to pass nothing for the `data` argument and convert to an empty dictionary to keep encoding consistent.
=> feat: allow non preapproved payloads for run tokens

evervault/crypto/client.py, tests/test_evervault.py
`bytearray`s were throwing an error on encryption
Casting `bytearray`s to `bytes`
=> fix: allow encryption of bytearrays

evervault/__init__.py, evervault/client.py, evervault/crypto/client.py, evervault/errors/evervault_errors.py, tests/test_evervault.py
We do not support decryption of files >25MB so an error should be thrown if an attempt is made to encrypt a file larger than this size
Added a max file size, compared the file size with this max
=> feat: throw error on file size too large

evervault/crypto/client.py, tests/test_evervault.py
File encryption format now included a crc32 checksum
Added the crc32 checksum to the end of the file computed with binascii in Python's standard library
Added tests to ensure it is added.
=> Update Python SDK to add CRC32 checksum

.github/workflows/test.yml, README.md, tests/test_evervault.py
The test actions were [failing with a weird error](https://github.com/evervault/evervault-python/actions/runs/4874386476/jobs/8738460718), which wasn't occurring locally. This is blocking updates to the SDK.
* Bump the version of poetry used in the workflow
* Fix a couple of file encryption tests
=> ci: fix tests workflow

README.md, evervault/cages_v2.py, pyproject.toml, tests/test_evervault.py
User's may want to re-deploy their Cage with different PCRs, or signed with a different cert. This would allow users to attempt to attest their Cage using the old set of PCRs and the new set of PCRs. This would allow their client to keep making successful connections during a deployment.
* Bump version of python attestation bindings used
* Coerce data given by user into a list, and pass that into the attestation bindings
=> feat(cages attestation): allow users to pass in a list of sets of PCRs for attesting their Cages

README.md, evervault/__init__.py, evervault/client.py, evervault/crypto/client.py, evervault/http/request.py, pyproject.toml, tests/test_evervault.py, tests/test_handling_cert.py, tests/test_handling_requests.py, tests/test_outbound_relay_config.py
BREAKING CHANGE: The UUID of the App is now required when initialising the SDK
Support is being added for the new `decrypt()` function. We will now require both the API key and the App UUID to perform authorization.
- Include the `app_uuid` as a required argument to `init()`
- Include `decrypt()` function
- Update minimum Python version to `Python3.7`
- Update cryptography version to `^41.0.0`
- Update `flake8` and `black` dependency versions
BREAKING CHANGE: The UUID of the App is now required when initialising the SDK
=> feat!: Require App UUID when initialising the SDK

.github/workflows/release.yml
Semantic release pushed a breaking change last week which prevented releasing to Pypi
Update the version
=> chore(workflow): update semantic release version

CHANGELOG.md, pyproject.toml
Can't release with reverted changelog and project version
=> chore: Revert 3.0.0

README.md, evervault/__init__.py, evervault/client.py, evervault/http/request.py, tests/test_evervault.py
Need to support the creation of decrypt tokens in the Python SDK
- Add `create_client_side_decrypt_token()`
=> feat(tokens): adds support for creating decrypt tokens

.changeset/fresh-flies-drive.md, evervault/__init__.py, evervault/client.py, evervault/http/requestintercept.py, tests/test_evervault.py
Removing deprecated logic ahead of upcoming major version bump
Removed intercept and ignore domains
=> Deprecating intercept and ignore domains

.changeset/small-games-rest.md, .github/workflows/e2e.yml, .github/workflows/test.yml, evervault/__init__.py, pyproject.toml
Removing support for Python 3.7 ahead of upcoming major version bump
Removed 3.7 specific logic
Removed 3.7 from tests
=> Deprecating python 3 7

.changeset/new-wombats-compete.md, evervault/__init__.py, evervault/cages_v2.py, tests/test_attestatable_session.py
We deprecated the old attestation session, now we can remove it because we're doing a major release
Remove
=> Remove deprecated attestation

.changeset/happy-trains-exercise.md, evervault/__init__.py, evervault/enclaves.py, evervault/http/attestationdoc.py, evervault/http/pcrManager.py, tests/test_enclave_attestatable_session.py, tests/test_pcrs_manager.py
New hostname
Add new function attestable_enclave_session() which returns a http session to use for attesting requests to enclaves.
Mark the old attestatble_cage_session() as deprecated as it will be removed in future versions.
=> [SPE-1025] Add enclave function to python SDK

.github/workflows/release.yml
Should fix access denied when releasing the SDK
- Not sure why we are using a PAT for checkout, removed to auto use actions token
- Bumped checkout version
=> fix: remove PAT token and use checkout v3

.changeset/ten-kiwis-glow.md, poetry.lock, pyproject.toml
Bumping cryptography to a version greater than `43`.
=> chore: bump dependancy
